### ISSUE TITLE
AUR support

### ISSUE THREAD

**Issue by lll2yu** [kanishka-linux/ReadManga#3]
Hello there, found this software from a 4chan thread,it's what I was looking for, thanks for making this. I noticed that you have put together PKGBUILD for this software and many of your other projects. Is there a reason that you didn't put up the packages on AUR?

**Comment by kanishka-linux** [comment]
I've written PKGBUILD without following any proper convention and without using setup.py. They are working properly, but still I feel that they are not written properly, that's why I haven't submitted to AUR. Recently few fellow arch users have submitted proper PKGBUILD to my other project (kawaii-player) to AUR. Maybe you can take a look at them to see what I was missing.

By the way, it is good to see that this application is still working. I haven't checked it since many months ago. I hope you'll enjoy it.

**Comment by lll2yu** [comment]
Thanks for the clarification. 
The application is working as intended and smoothly. Do you plan to continue working on this project in near future?

**Comment by kanishka-linux** [comment]
I'm not sure about it. I wrote it mainly to test some threading concepts and dynamic widget creation. If some gui elements will break due to new features or some library mismatch in new qt version, then I'll try to fix them. But if some source sites will break, then I'm not sure about fixing them.
